const dummyData = [
   {word:'apple',
    meaning:'사과'},
    {word:'before',
    meaning:'이전의'},
    {word:'clean',
    meaning:'깨끗한'},
    {word:'dummy',
    meaning:'가짜의'},
    {word:'emergent',
    meaning:'긴급한'},
    {word:'famous',
    meaning:'유명한'},
    {word:'give',
    meaning:'주다'},
    {word:'humble',
    meaning:'검소한'},
    {word:'ingrave',
    meaning:'조각하다'},
    {word:'jungle',
    meaning:'밀림'},
    {word:'korea',
    meaning:'한국'},
]
export default dummyData;